### ISSUE TITLE
Cannot find module '../build/Debug/pty.node'

### ISSUE THREAD

**Issue by Lalit64** [saisandeepvaddi/how-to-create-web-terminals#21]
Hi, @saisandeepvaddi I downloaded the source code fresh and hit up the server but I noticed an error. So I started up the client and I got the same error saying

<img width="2200" alt="image" src="https://user-images.githubusercontent.com/79628080/141090251-f4a45163-dad5-4de4-bb48-796c45cd0b90.png">
 
Do you know how to fix it?

**Comment by Lalit64** [comment]
You have to update the version of node-pty, sorry for the trouble.

**Comment by FormalSnake** [comment]
Even aftter update it still doesnt find it in the electron sample.
